name: gloom303
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32144
title: Gloom303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71934774-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4c4d3'
    - '#272826'
    - '#926b8c'
    - '#45786e'
    - '#68a8d9'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
