name: gloom303
favicon: null
layout_spectrum: 0.4341814185027033
typography_spectrum: 0.9138182089664042
title: Gloom303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71934774-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.045118402456864715
  lightness: 0.4581048048567027
  saturation: 0.8622835581190884
  rhythmicContrast: 0.4636372209060937
purpose: []
